### ISSUE TITLE
Antisampling

### ISSUE THREAD

**Issue by padak** [keboola/google-analytics-bundle#1]
Hi,
instead of existing [antisampling](http://wiki.keboola.com/home/keboola-connection/devel-space/integrating-with-kbc/extractors/google-analytics#TOC-Sampling) can we use [this](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#samplingLevel) "new"  antisampling approach in our GA extractor?

Thanks,
Peter

**Comment by MiroCillik** [comment]
It is already implemented, but for the lowest sampling possible, you still have to use the "old" method (I think).

**Comment by padak** [comment]
In that case, can you check this ticket https://keboola.zendesk.com/agent/tickets/4344 and tell me if I can close it? If so, it would be great if you note it in wiki docs, that there is native antisamplin XY.
thx!

**Comment by MiroCillik** [comment]
It's not a problem of extractor, so I think you can close it. You could add the link to [how antisampling works] (http://wiki.keboola.com/home/keboola-connection/devel-space/integrating-with-kbc/extractors/google-analytics#TOC-Sampling). There is said that you can't use "antisampling: 1" with "unique" metrics like `users`, see [this article] (https://support.google.com/analytics/answer/2992042?hl=en).

**Comment by padak** [comment]
Thanks!
